%%%
  VERSION:1
  LANGUAGE:ENGLISH
%%%

MODULE mAUTODESK

  PERS wobjdata wADSK0:=[FALSE,TRUE,"", [[1587.651,1696.886,804.1803],[0.0162324,0.0011719,-0.0014062,-0.9998666]],[[0,0,0],[1,0,0,0]]];
  PERS tooldata tADSK27:=[TRUE,[[-244.6702,-1.320775,239.6506],[0.7071068,0,-0.707168,0]],[40,[50,0,120],[1,0,0,0],0,0,0]];

  PERS speeddata v75:=[75,500,5000,1000];
  PERS speeddata v333:=[800,500,5000,1000];
  PERS speeddata v25:=[25,500,5000,1000];

  PROC main()
    ! Generated by AUTODESK Fusion CAM 2605.1.52
    ! Creation date: 2026-02-02 1:19:36 p.m.

    ! Acceleration and jerk/ramp (percentage)
    AccSet 20,20;

    ! Configurations
    ConfJ\On;
    ConfL\Off;

    ! Load Tool
    !Tool_Change tADSK27;

    ! Spindle On/Speed
    !Spindle_ON 15000;

    p2D_Contour60;
    p2D_Contour61;
    p2D_Contour63;
    p2D_Contour64;

    ! Spindle OFF
    ! setdo Local_IO_0_DO11, 0;

    ConfJ\On;
    ConfL\On;
    Stop;
  ENDPROC
ENDMODULE
