%%%
  VERSION:1
  LANGUAGE:ENGLISH
%%%

MODULE mAUTODESK

  PERS speeddata v114:=[114,500,5000,1000];
  PERS speeddata v17:=[17,500,5000,1000];
  PERS speeddata v38:=[38,500,5000,1000];

  PROC main()
    ! Generated by AUTODESK Fusion CAM 2605.1.52
    ! Creation date: 2026-02-02 2:41:17 p.m.

    ! Acceleration and jerk/ramp (percentage)
    AccSet 20,20;

    ! Configurations
    ConfJ\On;
    ConfL\Off;

    ! Load Tool
    !Tool_Change tADSK23;

    ! Spindle On/Speed
    !Spindle_ON 15000;

    p2D_Contour71;

    ! Spindle Off
    !Spindle_OFF;

    ConfJ\On;
    ConfL\On;
    Stop;
  ENDPROC
ENDMODULE
